[68241] init
homesengland/he-ssp pull request #1
Opened 2023-06-07 09:24 UTC by pawelpwc

2023-06-07 09:38 UTC, dawid-pawulski approved these changes

2023-06-07 13:28 UTC, liquidtoon01 requested changes

2023-06-09 08:52 UTC, pawelpwc commented on azure-pipelines-build.yml
> +pool: "vmss-ado-chs-nonprod-001"
https://github.com/homesengland/he-aho-find-and-register/blob/main/azure-pipelines.yml copied from this repository. The 'vmss-ado-chs-nonprod-001' agent may have special permissions to download the HE packages in the pipeline. Confirm that the ubuntu-22.04 agent will work.

2023-06-09 08:53 UTC, pawelpwc commented on azure-pipelines.yml
> +pool: "vmss-ado-chs-nonprod-001"
Same case

2023-06-13 13:34 UTC, NigelStephenson commented on CODEOWNERS
CODEOWNERS should not be removed

2023-06-13 13:35 UTC, NigelStephenson commented on LICENSE
LICENSE should not be removed

2023-06-13 13:36 UTC, NigelStephenson commented on README.md
README.md should not be removed

2023-06-13 13:42 UTC, NigelStephenson commented on src/placeholder.txt
The src folder should be where the code sits for the application. Could you please move the solution file, Dockerfile, pipelines and project folders into src so that it matches the structure of the [pipeline-assessment repository](https://github.com/homesengland/he-pipeline-assessment)

2023-06-15 08:43 UTC, merged