Add ApplicationProjects handlers and repository
homesengland/he-ssp pull request #111
Opened 2023-07-18 18:54 UTC by dawid-pawulski

2023-07-19 05:54 UTC, lukasz-ciura-pwc requested changes

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/CommandHandlers/DeleteProjectCommand.cs
> +public record DeleteProjectCommand(LoanApplicationEntity LoanApplicationEntity, Guid ProjectId) : IRequest;
`LoanApplicationEntity` shouldn't be needed

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/Entities/ApplicationProjects.cs
> +
DeleteProject should be part of this aggregate.

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/Entities/Project.cs
> +public class Project
We need to talk about it ^_^

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/QueryHandlers/GetAllApplicationProjectsQueryHandler.cs
> +                                                new UserAccount(_loanUserContext.UserGlobalId, await _loanUserContext.GetSelectedAccountId().ConfigureAwait(false)));
`.ConfigureAwait(false)` is it needed?

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/QueryHandlers/GetProjectDetailsQuery.cs
> +public record GetProjectDetailsQuery(LoanApplicationId LoanApplicationId, Guid ProjectId) : IRequest<Project>;
To discuss: should Query Handles can return Entities?

2023-07-19 05:54 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/ApplicationProject/Repositories/ApplicationProjectsRepository.cs
> +        loanApplicationSessionModel.Timestamp = DateTime.Now;
Use `DateTimeProvider`. But I think we don't have to set it, CRM will do it for us.

2023-07-20 09:13 UTC, lukasz-ciura-pwc approved these changes

2023-07-20 10:10 UTC, jakub-lotko approved these changes

2023-07-20 13:10 UTC, merged