71481 Global Middleware to handle Exceptions
homesengland/he-ssp pull request #114
Opened 2023-07-19 09:07 UTC by pawelpwc

2023-07-20 08:17 UTC, lukasz-ciura-pwc requested changes

2023-07-20 08:20 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.WWW/Controllers/ErrorController.cs
> +        var data = _cacheService.GetValue<ErrorModel>($"{RouteConstants.ErrorPageNotFound}?key={key}");
External services (like Redis) should not be part of error handling process.

2023-07-27 07:29 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.Common/Services/MemoryCacheService.cs
> +    public void SetValue(string key, object value, int expireMinutes)
What is purpose of this method? BTW expireMinutes parameter is not used.

2023-07-27 07:29 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.Common/Models/Others/ErrorModel.cs
> +    public string StackTrace { get; set; }
IMHO, stack trace is not need. It can be just appended to Message property.

2023-07-27 10:37 UTC, dawid-pawulski approved these changes

2023-07-27 11:27 UTC, lukasz-ciura-pwc approved these changes

2023-07-27 11:45 UTC, merged