#ab95631 extend application endpoint
homesengland/he-ssp pull request #1430
Opened 2024-04-26 07:11 UTC by suskiwojciech

### 🛠 Changes being made

Summarize the changes you've made in this pull request.

### 📸 Screenshots (optional)

Insert some screenshots if you made UI changes.

### 🏎 Quality check

- [ ] Have you performed local tests?
- [ ] Are integration tests passing locally?
- [ ] Have you added some unit tests?
- [ ] Have you added some integration tests?
- [ ] Have you checked WCAG (included screenshot)

2024-04-26 09:14 UTC, jjankowski87 requested changes

2024-04-26 09:14 UTC, jjankowski87 commented on src/HE.CRM.AHP.Plugins/Services/Application/ApplicationService.cs
> +                    var site = _siteRepository.GetById(application.invln_Site.Id, new string[] {invln_Sites.Fields.invln_developingpartner,
Application partners could be different than Site partners, also Site can have multiple applications.
So application partners should be stored on application entity, not site.

2024-04-28 21:57 UTC, suskiwojciech commented on src/HE.CRM.AHP.Plugins/Services/Application/ApplicationService.cs
> +                    var site = _siteRepository.GetById(application.invln_Site.Id, new string[] {invln_Sites.Fields.invln_developingpartner,
To discus what about field: owner of the land during development and owner of the house after completion.

2024-05-02 06:27 UTC, Carq commented
https://github.com/homesengland/he-ssp/pull/1444/files

2024-05-02 06:27 UTC, closed without merging