#AB95971 admin user is not able to submit and request to edit application created by enhanced user and reverse
homesengland/he-ssp pull request #1454
Opened 2024-05-06 11:13 UTC by suskiwojciech

### 🛠 Changes being made

Summarize the changes you've made in this pull request.

### 📸 Screenshots (optional)

Insert some screenshots if you made UI changes.

### 🏎 Quality check

- [ ] Have you performed local tests?
- [ ] Are integration tests passing locally?
- [x] Have you added some unit tests?
- [ ] Have you added some integration tests?
- [ ] Have you checked WCAG (included screenshot)

2024-05-06 11:14 UTC, jjankowski87 approved these changes

2024-05-06 11:16 UTC, MichalSzrederPWC commented
Jakiś test automatyczny by się przydał do tego przypadku

2024-05-06 23:57 UTC, MichalSzrederPWC requested changes

2024-05-06 23:57 UTC, MichalSzrederPWC commented on src/HE.CRM.AHP.Plugins/Services/Application/ApplicationService.cs
> -            if (application != null && application.invln_organisationid.Id == new Guid(organisationId) && application.invln_contactid.Id == contact.Id)
Won't this allow every role to change application status? My understanding is right now it allows only the creator to edit, but if we remove this check it will allow everyone. What do you think?

2024-05-06 23:57 UTC, MichalSzrederPWC commented on src/HE.CRM.AHP.Plugins/Services/Application/ApplicationService.cs
> -            if (application != null && application.invln_organisationid.Id == new Guid(organisationId) && application.invln_contactid.Id == contact.Id)
Might consider adding an automated test for this case

2024-05-07 06:47 UTC, jjankowski87 commented on src/HE.CRM.AHP.Plugins/Services/Application/ApplicationService.cs
> -            if (application != null && application.invln_organisationid.Id == new Guid(organisationId) && application.invln_contactid.Id == contact.Id)
Verification of user roles is Portal responsibility which is already done. 
This check was preventing from changing status any user other than creator. What if creator is no longer able to edit (changed to view only) ?

2024-05-08 07:52 UTC, MichalSzrederPWC approved these changes

2024-05-08 08:24 UTC, merged