AB#99726 Added frontdoor decision persistance
homesengland/he-ssp pull request #1674
Opened 2024-06-14 16:24 UTC by MichalSzrederPWC

### 🛠 Changes being made

Added saving eligibility result on frontdoor project submit. Used hardcoded ints because appropriate enum was not present yet in crm.

### 📸 Screenshots (optional)

Insert some screenshots if you made UI changes.

### 🏎 Quality check

- [ ] Have you performed local tests?
- [ ] Are integration tests passing locally?
- [ ] Have you added some unit tests?
- [ ] Have you added some integration tests?
- [ ] Have you checked WCAG (included screenshot)

2024-06-17 05:33 UTC, jjankowski87 commented on src/HE.Investments.FrontDoor.Domain/Project/ProjectEntity.cs
> +        int? frontDoorDecision = null)
Use enum in domain entity, map to DTO on repository level

2024-06-17 05:33 UTC, jjankowski87 commented on src/HE.Investments.FrontDoor.WWW/Controllers/ProjectController.cs
> +        await _mediator.Send(new UpdateFrontDoorDecisionCommand(FrontDoorProjectId.From(projectId), applicationType), cancellationToken);
I belive this call should be below if, so decision is saved when there is no error in answers

2024-06-17 05:38 UTC, Carq requested changes
As we spoke the whole logic related with saving decision should be inside ProjectEntity

2024-06-17 13:06 UTC, MichalSzrederPWC commented on src/HE.Investments.FrontDoor.WWW/Controllers/ProjectController.cs
> +        await _mediator.Send(new UpdateFrontDoorDecisionCommand(FrontDoorProjectId.From(projectId), applicationType), cancellationToken);
moved logic to projectentity

2024-06-17 13:06 UTC, MichalSzrederPWC commented on src/HE.Investments.FrontDoor.Domain/Project/ProjectEntity.cs
> +        int? frontDoorDecision = null)
done

2024-06-17 13:06 UTC, MichalSzrederPWC commented
> As we spoke the whole logic related with saving decision should be inside ProjectEntity

done

2024-06-18 04:46 UTC, jjankowski87 approved these changes

2024-06-18 09:37 UTC, Carq approved these changes

2024-06-18 09:38 UTC, merged