Max file size param moved to configuration
homesengland/he-ssp pull request #173
Opened 2023-08-21 14:11 UTC by pawelpwc

2023-08-22 06:11 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.WWW/Controllers/CompanyStructureV2Controller.cs
> +            if (viewModel.CompanyInfoFile.Length > _appConfig.MaxFileSizeInMegabytes * 1024 * 1024)
Validation of file size is in `CompanyStructureValidator` - so this code is not needed.

2023-08-22 06:11 UTC, lukasz-ciura-pwc requested changes

2023-08-22 06:11 UTC, lukasz-ciura-pwc commented on src/HE.InvestmentLoans.Common/Exceptions/FileException.cs
> +public class FileException : Exception
This exception is not needed.

2023-08-23 07:25 UTC, lukasz-ciura-pwc approved these changes

2023-08-23 07:36 UTC, burzynskijakub approved these changes

2023-08-23 08:25 UTC, merged