Add organization search
homesengland/he-ssp pull request #191
Opened 2023-08-24 14:14 UTC by jakub-lotko

- add pagination control
- add tests

2023-08-29 12:04 UTC, lukasz-ciura-pwc requested changes

2023-08-31 09:02 UTC, lukasz-ciura-pwc approved these changes

2023-08-31 09:02 UTC, lukasz-ciura-pwc commented on src/HE.Investments.Organisation/Config/ServiceCollectionExtensions.cs
❤

2023-08-31 09:02 UTC, lukasz-ciura-pwc commented on src/HE.Investments.Organisation/Services/IOrganizationCrmSearchService.cs
> +internal interface IOrganizationCrmSearchService
Put interface to separate file.

2023-08-31 09:02 UTC, lukasz-ciura-pwc commented on src/HE.Investments.Organisation/Services/OrganisationSearchService.cs
> +    private async Task<OrganisationSearchResult> GetOrganizationFromCompenyHousesApi(string organisationName, PagingQueryParams pagingParams, CancellationToken cancellationToken)
Typo GetOrganizationFrom**Compeny**HousesApi

2023-08-31 09:02 UTC, lukasz-ciura-pwc commented on src/HE.Investments.Organisation/Services/OrganisationSearchService.cs
>          {
Exception should be logged.

2023-08-31 10:11 UTC, dawid-pawulski approved these changes

2023-08-31 10:11 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.BusinessLogic/Organization/QueryHandlers/SearchOrganizationsHandler.cs
> +    public SearchOrganizationsHandler(IOrganisationSearchService searchService)
We can change that to SearchOrganizationsQueryHandler

2023-08-31 10:11 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.WWW/Controllers/OrganizationController.cs
> +    public IActionResult SearchOrganizationPost(OrganizationViewModel organization)
To be consistent with other controllers we don't need to add "Post" at the end of this method name

2023-08-31 10:11 UTC, dawid-pawulski commented on src/He.AspNetCore.Mvc.Gds.Components/TagHelpers/Pagination/GdsPaginationTagHelper.cs
> +            output.TagName = "nav";
We can add strings from this file to constants

2023-08-31 10:38 UTC, merged