AB#105261 Add feature flag for errors
homesengland/he-ssp pull request #2001
Opened 2024-08-21 16:44 UTC by dawid-pawulski

### 🛠 Changes being made

Add feature flag for errors

### 🏎 Quality check

- [ ] Have you performed local tests?
- [ ] Are integration tests passing locally?

2024-08-21 16:47 UTC, dawid-pawulski commented
needs to be tested tomorrow -> waiting for CRM

2024-08-22 05:14 UTC, Carq approved these changes

2024-08-22 05:24 UTC, jjankowski87 approved these changes

2024-08-22 07:56 UTC, jjankowski87 requested changes

2024-08-22 07:56 UTC, jjankowski87 commented on src/HE.Investments.Common.WWW/Infrastructure/ErrorHandling/ExceptionFilterAttribute.cs
> +    public override async void OnException(ExceptionContext context)
you should use OnExceptionAsync

2024-08-26 04:55 UTC, jjankowski87 approved these changes

2024-08-26 05:53 UTC, merged