Feature/funding draft
homesengland/he-ssp pull request #289
Opened 2023-09-20 19:21 UTC by dawid-pawulski

2023-09-21 14:03 UTC, Carq approved these changes

2023-09-22 06:24 UTC, jakub-lotko requested changes

2023-09-22 06:24 UTC, jakub-lotko commented on src/HE.InvestmentLoans.Contract/Funding/FundingViewModel.cs
> +    public bool IsProgress()
I think IsInProgress sound better

2023-09-22 06:24 UTC, jakub-lotko commented on src/HE.InvestmentLoans.Contract/Funding/ValueObjects/GrossDevelopmentValue.cs
> +        _ = decimal.TryParse(grossDevelopmentValue, NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out var parsedValue);
Is there a need to use TryParse instead of Parse? As I can see parsing result is not used anywhere.

2023-09-22 06:24 UTC, jakub-lotko commented on src/HE.Investments.IntegrationTests/Loans/FundingSection/Order02GrossDevelopmentValueIntegrationTests.cs
> +    public async Task Order01_ShouldDisplayValidationError_WhenProvidedValueIsText()
WhenProvidedValueIsNotADecimalNumber would be more precise because technically this value is always a text

2023-09-22 06:24 UTC, jakub-lotko commented on src/HE.Investments.IntegrationTests/Loans/FundingSection/Order03EstimatedTotalCostsIntegrationTests.cs
> +    public async Task Order01_ShouldDisplayValidationError_WhenProvidedValueIsText()
Same as GDV

2023-09-22 06:45 UTC, jakub-lotko approved these changes

2023-09-22 06:46 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.Contract/Funding/ValueObjects/GrossDevelopmentValue.cs
> +        _ = decimal.TryParse(grossDevelopmentValue, NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out var parsedValue);
After discussion we are not changing it

2023-09-22 06:49 UTC, merged