Withdrawn draft
homesengland/he-ssp pull request #312
Opened 2023-09-26 10:16 UTC by dawid-pawulski

2023-09-26 10:42 UTC, Carq requested changes

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/Repositories/LoanApplicationRepository.cs
> +    public async Task Withdraw(LoanApplicationId loanApplicationId, WithdrawReason withdrawReason, ApplicationStatus applicationStatus, CancellationToken cancellationToken)
We should not pass `applicationStatus` here. The Withdraw mehod should have hardcoded `invln_statusexternal` status

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/Repositories/LoanApplicationRepository.cs
> +            invln_withdrawreason = withdrawReason.ToString(),
` invln_withdrawreason` -> ` invln_changereason` ? Probably we will use it also for On Hold actions

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.Contract/Application/Commands/WithdrawLoanApplicationCommand.cs
> +public record WithdrawLoanApplicationCommand(LoanApplicationId LoanApplicationId, string WithdrawReason, string ApplicationStatus) : IRequest<OperationResult>;
Do we need ApplicationStatus here? I think command name is explicit saying that desire status is withdraw.

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.WWW/Models/NotificationModel.cs
> +            return "govuk-notification-banner--success";
css styles should be part of the model.  This is View logic.

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.WWW/Controllers/LoanApplicationV2Controller.cs
> +    public async Task<IActionResult> ApplicationDashboardPost(Guid id, string buttonValue, string applicationStatus)
Do we need this method? Could we just use button with links to redirect to withrown screen?

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/CommandHandlers/WithdrawLoanApplicationCommandHandler.cs
> +            return domainValidationException.OperationResult;
Please log exception as warning.

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/Repositories/LoanApplicationRepository.cs
> +    public async Task Withdraw(LoanApplicationId loanApplicationId, WithdrawReason withdrawReason, ApplicationStatus applicationStatus, CancellationToken cancellationToken)
It would be nice to execute that method inside of LoanApplicationEntity.Withdraw (the same way as it is for submit

2023-09-26 10:42 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/CommandHandlers/WithdrawLoanApplicationCommandHandler.cs
> +            var newApplicationStatus = applicationStatus == ApplicationStatus.ApplicationSubmitted ? ApplicationStatus.Withdrawn : ApplicationStatus.NA;
I think we could have two seperate command for "Removing" loan and for "Withdrawing" loan

2023-09-26 12:16 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/Repositories/LoanApplicationRepository.cs
> +    public async Task Withdraw(LoanApplicationId loanApplicationId, WithdrawReason withdrawReason, ApplicationStatus applicationStatus, CancellationToken cancellationToken)
applicationStatus deleted

2023-09-26 12:17 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/Repositories/LoanApplicationRepository.cs
> +            invln_withdrawreason = withdrawReason.ToString(),
change applied

2023-09-26 12:17 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.Contract/Application/Commands/WithdrawLoanApplicationCommand.cs
> +public record WithdrawLoanApplicationCommand(LoanApplicationId LoanApplicationId, string WithdrawReason, string ApplicationStatus) : IRequest<OperationResult>;
Status deleted

2023-09-26 12:18 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.WWW/Models/NotificationModel.cs
> +            return "govuk-notification-banner--success";
done

2023-09-26 12:18 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.WWW/Controllers/LoanApplicationV2Controller.cs
> +    public async Task<IActionResult> ApplicationDashboardPost(Guid id, string buttonValue, string applicationStatus)
done

2023-09-26 12:18 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/CommandHandlers/WithdrawLoanApplicationCommandHandler.cs
> +            return domainValidationException.OperationResult;
done

2023-09-26 12:18 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.BusinessLogic/LoanApplication/CommandHandlers/WithdrawLoanApplicationCommandHandler.cs
> +            var newApplicationStatus = applicationStatus == ApplicationStatus.ApplicationSubmitted ? ApplicationStatus.Withdrawn : ApplicationStatus.NA;
done

2023-09-27 05:07 UTC, Carq commented on src/HE.InvestmentLoans.WWW/Views/LoanApplicationV2/Withdraw.cshtml
> +@inject IAppConfig appConfig
Is it needed?

2023-09-27 05:08 UTC, Carq approved these changes

2023-09-27 06:59 UTC, PiotrSamb approved these changes

2023-09-27 07:05 UTC, merged