document service for portal
homesengland/he-ssp pull request #418
Opened 2023-10-13 15:52 UTC by pawelpwc

2023-10-16 09:58 UTC, dawid-pawulski approved these changes

2023-10-16 12:22 UTC, Carq requested changes

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.WWW/Controllers/CompanyStructureV2Controller.cs
> +            var result = await _mediator.Send(
There should be only one command which saves organization information and upload files.
Upload should happen only after clicking "Continue" button"

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CommandHandlers/ProvideMoreInformationAboutOrganizationFileCommandHandler.cs
> +                IAppConfig appConfig,
AppConfig is not needed.

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.WWW/wwwroot/javascripts/ExistingCompany.file-validation.js
> -function validateFileSize() {
Please Revert the change. File should be validation on client site before uploading to the server.

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.Contract/CompanyStructure/ValueObjects/OrganisationMoreInformationFiles.cs
> +public class OrganisationMoreInformationFiles : ValueObject
Imho. There should be one Value Object which aggregates all files and validate all files. We can discuss this offline.

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.Contract/CompanyStructure/ValueObjects/OrganisationMoreInformationFile.cs
> +    public OrganisationMoreInformationFile(FileData file, int maxFileSizeInMb)
PLease revert of this change. Classes from external service cannot be part Domain classes (ValueObjects, entities)

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/QueryHandlers/GetCompanyStructureFilesQueryHandler.cs
> +        var result = await _documentService.GetTableRowsAsync(new FileTableFilter()
All communication with Document service (upload, download, remove etc)  should be part of the Data layer so it should be in repositories.

2023-10-16 12:22 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CommandHandlers/CompanyStructureBaseCommandHandler.cs
> +    protected async Task<OperationResult> Perform(Func<CompanyStructureEntity, UserAccount, Task> action, LoanApplicationId loanApplicationId, CancellationToken cancellationToken)
This is needed only in one command handler, so you don't have use base command handler, just create own one and please revert that change.

2023-10-16 12:23 UTC, Carq requested changes

2023-10-16 12:23 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CompanyStructureEntity.cs
> +    public OrganisationMoreInformationFiles? MoreInformationFiles { get; private set; }
It should be set via ctor

2023-10-16 12:27 UTC, Carq requested changes

2023-10-16 12:27 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CommandHandlers/ProvideMoreInformationAboutOrganizationFileCommandHandler.cs
> +                        CreateDate = DateTime.Now,
`IDateTimeProvider.Now` should be used.

2023-10-16 12:27 UTC, Carq commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CommandHandlers/ProvideMoreInformationAboutOrganizationFileCommandHandler.cs
> +                        Creator = userAccount.AccountName,
AccountName is the organisation name. You should put First and Last name of the user.

2023-10-17 07:39 UTC, pawelpwc commented on src/HE.InvestmentLoans.BusinessLogic/CompanyStructure/CommandHandlers/ProvideMoreInformationAboutOrganizationFileCommandHandler.cs
> +                IAppConfig appConfig,
Is needed

2023-10-17 07:41 UTC, pawelpwc commented on src/HE.InvestmentLoans.Contract/CompanyStructure/ValueObjects/OrganisationMoreInformationFiles.cs
> +public class OrganisationMoreInformationFiles : ValueObject
The class validate all files (files.count)

2023-10-17 13:05 UTC, Carq commented on src/HE.InvestmentLoans.Contract/CompanyStructure/ValueObjects/OrganisationMoreInformationFile.cs
> +    public OrganisationMoreInformationFile(FileData file, int maxFileSizeInMb)
Why it was marked as resolved?

2023-10-18 10:50 UTC, Carq approved these changes

2023-10-18 10:51 UTC, merged