Added AHP Financial landing page
homesengland/he-ssp pull request #447
Opened 2023-10-20 06:47 UTC by rafalgajewski

2023-10-20 06:52 UTC, jjankowski87 approved these changes

2023-10-20 06:58 UTC, Carq commented on src/HE.Investment.AHP.WWW/Views/Finance/Index.cshtml
> +        <gds-h1 class="govuk-heading-xl">
WCAGs?

2023-10-20 07:30 UTC, Carq approved these changes

2023-10-23 13:12 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/Finance/Index.cshtml
> +        <gds-h1 class="govuk-heading-xl">
I've added landmarks - WCAG check now passed fine

2023-10-24 07:56 UTC, Carq requested changes
Please remove commented code.

2023-10-24 10:00 UTC, Carq approved these changes

2023-10-24 10:25 UTC, jjankowski87 approved these changes

2023-10-24 10:25 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/FinancialDetails/CommandHandlers/CreateFinancialDetailsCommandHandler.cs
> +
@Carq are stylecop rules configured properly for this project?

2023-10-24 10:25 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/FinancialDetails/CommandHandlers/FinancialDetailsCommandHandlerBase.cs
> +            ?? throw new NotFoundException(nameof(FinancialDetails), financialDetailsId);
I can see that this exception is already thrown in repository (and this is correct)  so it'll never be null and throw is not needed here

2023-10-24 10:25 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/HE.Investment.AHP.Domain.csproj
> +      <Folder Include="FinancialDetails\ValueObjects\" />
remove and fix formatting in line 18

2023-10-24 10:25 UTC, jjankowski87 commented on src/HE.Investment.AHP.WWW/Views/Finance/Index.cshtml.cs
> +public class Index : PageModel
this file is not needed and can be removed

2023-10-24 10:50 UTC, rafalgajewski commented on src/HE.CRM.Plugins/Services/Accounts/AccountService.cs
> +        //private readonly string _someoneElseRequested = "Someoneelse requested";
commented code removed

2023-10-24 11:10 UTC, Antek012 approved these changes

2023-10-24 11:25 UTC, rafalgajewski commented on src/HE.Investment.AHP.Contract/HE.Investment.AHP.Contract.csproj
> +  <ItemGroup>
removed

2023-10-24 11:25 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/FinancialDetails/CommandHandlers/FinancialDetailsCommandHandlerBase.cs
> +            ?? throw new NotFoundException(nameof(FinancialDetails), financialDetailsId);
removed

2023-10-24 11:25 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/HE.Investment.AHP.Domain.csproj
> +      <Folder Include="FinancialDetails\ValueObjects\" />
removed and fixed

2023-10-24 11:26 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/Finance/Index.cshtml.cs
> +using Microsoft.AspNetCore.Mvc.RazorPages;
no, it's already removed

2023-10-24 11:26 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/FinancialDetails/Repositories/FinancialDetailsRepository.cs
> +        //if (projectToSave.IsNewlyCreated)
done

2023-10-24 11:27 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/FinancialDetails/CommandHandlers/CreateFinancialDetailsCommandHandler.cs
> +    //private readonly ILogger<CreateFinancialDetailsCommandHandler> _logger;
done

2023-10-24 11:27 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Controllers/FinanceController.cs
> +public class FinanceController : Controller
I think so, it will be added later on

2023-10-24 11:53 UTC, merged