69147 Optional radio buttons
homesengland/he-ssp pull request #46
Opened 2023-06-27 09:50 UTC by maciejzawad

2023-06-27 10:08 UTC, dawid-pawulski requested changes

2023-06-27 10:08 UTC, dawid-pawulski commented on src/HE.InvestmentLoans.WWW/Views/Shared/_CheckAnswersRow.cshtml
> +                }
This needs to be changed because you are now showing values for all flows. So if in the site we go a different path, you show "Not provided" for the second path. In this case, the second path should not be visible here. "Not provided" is shown only for questions that have not been answered within a given path

2023-06-27 10:28 UTC, maciejzawad commented on src/HE.InvestmentLoans.WWW/Views/Shared/_CheckAnswersRow.cshtml
> +                }
This is handled on different level ( at check answers partial view )

2023-06-27 12:26 UTC, jakub-lotko approved these changes

2023-06-28 07:42 UTC, dawid-pawulski approved these changes

2023-06-28 07:51 UTC, merged