AB#87573 added delivery phase name part
homesengland/he-ssp pull request #849
Opened 2024-01-05 13:02 UTC by rafalgajewski

2024-01-07 22:31 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/Name.cshtml
> +        <vc:numeric-text-input header="@title"
Fixed

2024-01-07 22:31 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/New.cshtml
> +@using HE.Investment.AHP.WWW.Models.Delivery;
I removed one of the views

2024-01-07 22:34 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Controllers/DeliveryPhaseController.cs
> +    public async Task<IActionResult> Name([FromRoute] string applicationId, [FromRoute] string deliveryPhaseId, CancellationToken cancellationToken)
Since it is a list of entities I think it easier to handle like it is now when each action has its own responsibility and in addition those to actions has different urls

2024-01-08 05:49 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        deliveryPhases.Add(deliveryPhase);
Add method CreateDeliveryPhase inside DeliveryPhasesEntity aggregate, which will accept only Name value object.
It already have ApplicationBasicInfo. Also it should check for name uniqueness.

2024-01-08 05:49 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/ValueObjects/DeliveryPhaseId.cs
> +    public static DeliveryPhaseId New() => new(Guid.NewGuid().ToString());
Id for newly created entity It will be returned by CRM, not created by us

2024-01-08 05:49 UTC, jjankowski87 commented on src/HE.Investment.AHP.WWW/Controllers/DeliveryPhaseController.cs
>      [HttpGet("new")]
Maybe change route for new delivery phase to empty string? Will it look cleaner?

2024-01-08 05:49 UTC, jjankowski87 commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/Name.cshtml
> +    <vc:back-link-with-callback url="@Url.Action("Back", "DeliveryPhase")" />
Back should redirect to DeliveryController, List action

2024-01-08 08:35 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Controllers/DeliveryPhaseController.cs
>      [HttpGet("new")]
I would rtather change it to match domain action so HttpGet("create"). What do you think?

2024-01-08 11:24 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        deliveryPhases.Add(deliveryPhase);
Added

2024-01-08 11:24 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/ValueObjects/DeliveryPhaseId.cs
> +    public static DeliveryPhaseId New() => new(Guid.NewGuid().ToString());
I used original code

2024-01-08 11:25 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/Name.cshtml
> +    <vc:back-link-with-callback url="@Url.Action("Back", "DeliveryPhase")" />
Changed

2024-01-08 12:04 UTC, Antek012 approved these changes

2024-01-08 12:04 UTC, Antek012 commented on src/HE.Investment.AHP.Domain/Delivery/Entities/DeliveryPhaseEntity.cs
> +        Name = deliveryPhaseName;
You should use modificationTracker to not omit data change.

2024-01-08 12:14 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        var deliveryPhase = deliveryPhases.CreateDeliveryPhase(request.DeliveryPhaseName);
According to our agreements, domain methods should accept value objects as a parameter

2024-01-08 12:14 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/Entities/DeliveryPhasesEntity.cs
> +        var deliveryPhase = new DeliveryPhaseEntity(_application, name, Status, new List<HomesToDeliverInPhase>());
you should hardcode InProgress status, as it's single delivery phase status not whole section

2024-01-08 12:14 UTC, jjankowski87 commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/Name.cshtml
> +    var title = "Name your delivery phase";
Add test for view

2024-01-08 14:51 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Controllers/DeliveryPhaseController.cs
>      [HttpGet("new")]
Renamed to Create

2024-01-08 14:52 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/Entities/DeliveryPhaseEntity.cs
> +        Name = deliveryPhaseName;
Implemented modification tracker

2024-01-08 14:52 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        var deliveryPhase = deliveryPhases.CreateDeliveryPhase(request.DeliveryPhaseName);
switched to domain value object as input

2024-01-08 14:52 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/Entities/DeliveryPhasesEntity.cs
> +        var deliveryPhase = new DeliveryPhaseEntity(_application, name, Status, new List<HomesToDeliverInPhase>());
Done

2024-01-08 14:53 UTC, rafalgajewski commented on src/HE.Investment.AHP.WWW/Views/DeliveryPhase/Name.cshtml
> +    var title = "Name your delivery phase";
Test added

2024-01-08 15:21 UTC, Carq approved these changes

2024-01-08 15:21 UTC, Carq commented on src/HE.Investment.AHP.Contract/Delivery/Commands/DeliveryCommandBase.cs
> +public abstract record DeliveryCommandBase(string ApplicationId) : IRequest<OperationResult>;
Is it duplicated by `IUpdateDeliveryPhaseCommand`?

2024-01-08 15:21 UTC, Carq commented on src/HE.Investment.AHP.Contract/Delivery/DeliveryPhaseId.cs
> +public record DeliveryPhaseId(string Id);
DeliveryPhaseId already exists in Domain, we need to move it to contract.

2024-01-08 22:48 UTC, rafalgajewski commented on src/HE.Investment.AHP.Contract/Delivery/Commands/DeliveryCommandBase.cs
> +public abstract record DeliveryCommandBase(string ApplicationId) : IRequest<OperationResult>;
It is, I removed it

2024-01-09 05:51 UTC, jjankowski87 requested changes

2024-01-09 05:51 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        return OperationResult.Success(new DeliveryPhaseId(deliveryPhaseId.Value));
1. OperationResult.CheckErrors throws exception which is not thrown. So app will crash? 🤔
2. Also your using Result to return result of async function in sync way. 
3. Another thing which I believe is wrong, is that CreateDeliveryPhase method accepts nullable name, it should be required.
4. You need to change returned type of Command to nullable Id, as in case of error Delivery Phase will not be created

So something like this would solve all issues:
```
var account = await _accountUserContext.GetSelectedAccount();

try
{
	var deliveryPhase = deliveryPhases.CreateDeliveryPhase(new DeliveryPhaseName(request.DeliveryPhaseName));
	_deliveryPhaseRepository.Save(deliveryPhase, account.SelectedOrganisationId(), cancellationToken)

	return new OperationResult<DeliveryPhaseId?>(deliveryPhase.Id);
}
catch (DomainValidationException domainValidationException)
{
	return new OperationResult<DeliveryPhaseId?>(domainValidationException.OperationResult.Errors, null);
}
```

2024-01-09 08:17 UTC, Antek012 approved these changes

2024-01-09 08:17 UTC, Antek012 commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        return OperationResult.Success(new DeliveryPhaseId(deliveryPhaseId.Value));
Ad1. DomainValidationException is catch by middleware so there is no need to catch it in CommandHandlers.
Ad3-True
Ad4 - true

2024-01-09 08:17 UTC, Antek012 commented on src/HE.Investment.AHP.Domain/Delivery/Entities/DeliveryPhaseEntity.cs
> +    public void ProvideName(DeliveryPhaseName? deliveryPhaseName)
JJ is right.
Entity property should be nullable, but this method param should not.
If you want to call ProvideName value should be provided.

2024-01-09 08:17 UTC, Antek012 commented on src/HE.Investment.AHP.WWW/Workflows/DeliveryPhaseWorkflow.cs
> +        _machine.Configure(DeliveryPhaseWorkflowState.Create)
please extend tests

2024-01-09 08:22 UTC, jjankowski87 commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        return OperationResult.Success(new DeliveryPhaseId(deliveryPhaseId.Value));
so it should be something like this:
```
var account = await _accountUserContext.GetSelectedAccount();
var deliveryPhase = deliveryPhases.CreateDeliveryPhase(new DeliveryPhaseName(request.DeliveryPhaseName));
_deliveryPhaseRepository.Save(deliveryPhase, account.SelectedOrganisationId(), cancellationToken)

return new OperationResult<DeliveryPhaseId?>(deliveryPhase.Id);
```

2024-01-09 08:47 UTC, rafalgajewski commented on src/HE.Investment.AHP.Contract/Delivery/DeliveryPhaseId.cs
> +public record DeliveryPhaseId(string Id);
to be updated later in separate pr

2024-01-09 09:05 UTC, rafalgajewski commented on src/HE.Investment.AHP.Domain/Delivery/CommandHandlers/CreateDeliveryPhaseCommandHandler.cs
> +        return OperationResult.Success(new DeliveryPhaseId(deliveryPhaseId.Value));
changes were implemented

2024-01-09 10:12 UTC, jjankowski87 approved these changes

2024-01-09 23:59 UTC, merged